# Generated by Django 4.0.6 on 2022-07-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
